### ISSUE TITLE
--resize_images failing

### ISSUE THREAD

**Issue by GantMan** [DiUS/MaskRCNN-utils#1]
Not sure why, but the resize is failing with this trace
```
Traceback (most recent call last):
  File "labelbox_parser.py", line 72, in <module>
    image, padding = resize_image_to_height(image)
  File "labelbox_parser.py", line 32, in resize_image_to_height
    image = np.pad(image, padding, mode='constant', constant_values=0)
  File "/Users/gantlaborde/miniconda3/lib/python3.7/site-packages/numpy/lib/arraypad.py", line 1172, in pad
    pad_width = _as_pairs(pad_width, narray.ndim, as_index=True)
  File "/Users/gantlaborde/miniconda3/lib/python3.7/site-packages/numpy/lib/arraypad.py", line 949, in _as_pairs
    raise ValueError("index can't contain negative values")
ValueError: index can't contain negative values
```

I tried looking up "index can't contain negative values" but this doesn't seem common.

Everything works without the resize param.

**Comment by GantMan** [comment]
height=400 was too small.  All my images were too big, so it was causing negative values when you subtract `h` on line 27 and 28.

I bumped my height up, but I'm sure there's a better solution.
